### ISSUE TITLE
Windows python3 executable fix

### ISSUE THREAD

**Issue by brokedba** [XargsUK/checkov-prismaless-vscode#2]
Hi , awesome fork mate. I discovered it while I was presenting checkov to a crowd after my bridgecrew trial has ended.
Thanks for saving my ass.

little bug I faced in windows 11 is that even after installing pipenv  the code was running python3 --version. but in windows 11 at least python3 executable is named python.exe 
![image](https://github.com/XargsUK/checkov-prismaless-vscode/assets/29458929/02d57b93-702f-4399-a71b-e013d4735a15)

 which caused the below error.
```
[info]: Trying to install Checkov using pipenv. 
[debug]: Installation dir: c:\Users\myuser\AppData\Roaming\Code\User\globalStorage\xargsuk.checkov-prismaless\checkov-installation  
...
 [error]...python3 --version is not recognized as an internal or external command,\r\noperable program or batch file.\
```

Workaround: 
```
mklink "C:\Users\MyUser\Python\python3.exe" "C:\Users\MyUser\Python\python.exe"
```

ps: I'm behind the first 17 downloads while troubleshooting :p

**Comment by XargsUK** [comment]
@brokedba Thanks for submitting! Admittedly using WSL for this, though I do have Python installed on Windows. 

Currently in a branch, though I've updated the verifyPythonVersion to use python --version on Windows, and python3 on other OSes. I'm going to try to replicate the issue later today. 

One approach to this issue I've seen, specifically in the Ansible extension, is to allow users to specify the python environment directory and python executable location within the extension configuration: 

![image](https://github.com/XargsUK/checkov-prismaless-vscode/assets/51077147/8a8d8e22-fda8-4b50-b8d3-4929e51c4ac5)

I do like this approach. Will look into implementing in the future.

**Comment by XargsUK** [comment]
Hi @brokedba! Updated so that if python3 fails, and OS=Windows, then it will attempt to use python. If you continue to have issues, feel free to reply to this to reopen. 

Thanks again!

**Comment by brokedba** [comment]
@XargsUK , nah all good Brad , your fix is settles it. thanks for the speedy response. 
Appreciate your work ! and yea pipx seems perfect here. 
will spread the word for sure ! dope extension
#happyeaster
